### ISSUE TITLE
swag menu items turn blue upon clicking and not when hovered

### ISSUE THREAD

**Issue by HarshitNagar** [kanishk09/kickflip_studios#1]
The menu items' background should change to like grey upon hovering

**Comment by HarshitNagar** [comment]
May I fix this ?
could you help me with some where to start steps?

**Comment by kanishk09** [comment]
The drop down menu options are changing to light grey on hovering.
For starters learn to create basic html webpages and add styles using CSS.
You may go through the udemy course on Full stack development..ie. Devslopes on YouTube.
